#include<stdio.h>

int main() 
{
	int a, b, c, sum;
	a = b = c = 1;
	sum = 0;
	char name[50];
	printf("Input your name : ");
	gets_s(name);
	printf("Welcome %s\n", name);
	printf("The question is \n");
	printf("Each new term in the Fibonacci sequence is generated by adding the previous two terms.\n");
	printf("By starting with 1 and 2, the first 10 terms will be:\n");
	printf("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n");
	printf("By considering the terms in the Fibonacci sequence whose values do not exceed four million,\n");
	printf("find the sum of the even-valued terms.\n\n");
	for (;c <= 4000000;) 
	{
		if (c % 2 == 0)
		{
			sum += c;
		}
		c = a + b;
		a = b;
		b = c;
	}
	printf("Answer = %d ", sum);
	return 0;
}